import 'package:mytin/models/motion_tile.dart';

List<MotionTile> motionList = [
  MotionTile.fromJson({
    "id": 1,
    "name": "스쿼트",
    "part": "하체",
    "difficulty": "고급",
    "imageUrl": "https://0k-cal.com/wp-content/uploads/2020/10/sss.jpg",
  }),
  MotionTile.fromJson({
    "id": 2,
    "name": "윗몸일으키기",
    "part": "복부",
    "difficulty": "고급",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeYRnjj0wCD5BjexjsE4IKh4NIW7gqrI7t5Q&usqp=CAU",
  }),
  MotionTile.fromJson({
    "id": 3,
    "name": "명상",
    "part": "어딘가",
    "difficulty": "신급",
    "imageUrl": "https://buddhayana2018504915002.files.wordpress.com/2018/11/417.jpg?w=500",
  }),
  MotionTile.fromJson({
    "id": 4,
    "name": "기도",
    "part": "어딘가",
    "difficulty": "신급",
    "imageUrl": "https://t1.daumcdn.net/cfile/tistory/252D9B3F549283D10D",
  }),
  MotionTile.fromJson({
    "id": 5,
    "name": "굿",
    "part": "전신",
    "difficulty": "상급",
    "imageUrl": "https://t1.daumcdn.net/cfile/blog/1467671E4A14B73E39",
  }),
  MotionTile.fromJson({
    "id": 6,
    "name": "취권",
    "part": "간",
    "difficulty": "중급",
    "imageUrl": "https://t1.daumcdn.net/cfile/tistory/99B91B485BBB588E32",
  }),
  MotionTile.fromJson({
    "id": 7,
    "name": "다구리",
    "part": "전신",
    "difficulty": "중급",
    "imageUrl": "https://i.ytimg.com/vi/4lHEAFNSHJU/maxresdefault.jpg",
  }),
  MotionTile.fromJson({
    "id": 8,
    "name": "공중부양",
    "part": "전신",
    "difficulty": "신급",
    "imageUrl": "https://pds.joins.com/news/component/joongang_sunday/201811/03/8d1f6a86-3658-40e1-879b-5b48b0ba12a1.jpg",
  }),
  MotionTile.fromJson({
    "id": 9,
    "name": "멈춰!",
    "part": "멈춰",
    "difficulty": "중급",
    "imageUrl": "https://s.gae9.com/trend/79453795e700b8e9.orig",
  }),
  MotionTile.fromJson({
    "id": 10,
    "name": "등산",
    "part": "하체",
    "difficulty": "고급",
    "imageUrl": "https://t1.daumcdn.net/cfile/blog/2255013A53CDB92C2F",
  }),
  MotionTile.fromJson({
    "id": 11,
    "name": "윗몸일으키기",
    "part": "복부",
    "difficulty": "고급",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeYRnjj0wCD5BjexjsE4IKh4NIW7gqrI7t5Q&usqp=CAU",
  }),
  MotionTile.fromJson({
    "id": 12,
    "name": "명상",
    "part": "어딘가",
    "difficulty": "신급",
    "imageUrl": "https://buddhayana2018504915002.files.wordpress.com/2018/11/417.jpg?w=500",
  }),
  MotionTile.fromJson({
    "id": 13,
    "name": "기도",
    "part": "어딘가",
    "difficulty": "신급",
    "imageUrl": "https://t1.daumcdn.net/cfile/tistory/252D9B3F549283D10D",
  }),
  MotionTile.fromJson({
    "id": 14,
    "name": "굿",
    "part": "전신",
    "difficulty": "상급",
    "imageUrl": "https://t1.daumcdn.net/cfile/blog/1467671E4A14B73E39",
  }),
  MotionTile.fromJson({
    "id": 15,
    "name": "취권",
    "part": "간",
    "difficulty": "중급",
    "imageUrl": "https://t1.daumcdn.net/cfile/tistory/99B91B485BBB588E32",
  }),
  MotionTile.fromJson({
    "id": 16,
    "name": "다구리",
    "part": "전신",
    "difficulty": "중급",
    "imageUrl": "https://i.ytimg.com/vi/4lHEAFNSHJU/maxresdefault.jpg",
  }),
  MotionTile.fromJson({
    "id": 17,
    "name": "공중부양",
    "part": "전신",
    "difficulty": "신급",
    "imageUrl": "https://pds.joins.com/news/component/joongang_sunday/201811/03/8d1f6a86-3658-40e1-879b-5b48b0ba12a1.jpg",
  }),
  MotionTile.fromJson({
    "id": 18,
    "name": "멈춰!",
    "part": "멈춰",
    "difficulty": "중급",
    "imageUrl": "https://s.gae9.com/trend/79453795e700b8e9.orig",
  }),
];