import 'package:mytin/models/routine_tile.dart';

List<RoutineTile> routineList = [
  RoutineTile.fromMap({
    "id": 1,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
  RoutineTile.fromMap({
    "id": 2,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
  RoutineTile.fromMap({
    "id": 3,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
  RoutineTile.fromMap({
    "id": 4,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
  RoutineTile.fromMap({
    "id": 5,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
  RoutineTile.fromMap({
    "id": 6,
    "name": "지옥의 루틴",
    "description": "개발은 언제끝나는 겨 하아... 집에 가고 싶다. 그래도 개발이 끝나기 전까지는 눈을 감을 수 없다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://lh3.googleusercontent.com/proxy/47TMjgRerEzqIBC2Pv1mbuMM0KOeAJH0B3RG2knhPYKE7Mf9aoOSjm2WPxSgmASRf9eyiUPqNZpva-otasXYilvGOUcbzl6GgFyu_36g_41acZiocHlfDEuhmKaKtrjsUXaAXyK4cgrYzGumENJ-fPyGaF_xLfy1BqeTqfs-i5IH3-Gimm_9Qwl5M8FTsB2M_3yCZJreaoHhNq1V67D8nVlMdW5BE3EQsAGO9aCwWB9u7wjD8KxMYf4YgxMTVIk15BQQatdOXN4F76VmsRk5_pXLvLZ7",
  }),
];