import 'package:mytin/models/routine_detail.dart';
import 'package:mytin/models/routine_tile.dart';

List<RoutineTile> routineList = [
  RoutineTile.fromMap({
    "id": 1,
    "name": "타바타 트레이닝",
    "description": "타바타는 단기간 고강도의 운동을 수행하며, 인터벌 트레이닝의 하나의 종류입니다.",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "상급",
    "type": "헬스",
    "imageUrl": "https://src.hidoc.co.kr/image/lib/2020/5/22/1590132842552_0.jpg",
  }),
  RoutineTile.fromMap({
    "id": 2,
    "name": "근력 운동 루틴",
    "description": "헬스장에서 했던 근력 운동의 트레이닝을 실시하는 루틴입니다.",
    "time": 20,
    "authority": Authority.admin,
    "difficulty": "중급",
    "type": "헬스",
    "imageUrl": "https://thumb.mt.co.kr/06/2020/07/2020070712585172596_3.jpg/dims/optimize/",
  }),
  RoutineTile.fromMap({
    "id": 3,
    "name": "걷기 루틴",
    "description": "걷는 것은 최고의 운동이라고 합니다. 걷는 것만으로 평생의 건강을 챙길 수 있습니다.",
    "time": 60,
    "authority": Authority.user,
    "difficulty": "초급",
    "type": "건강",
    "imageUrl": "https://post-phinf.pstatic.net/MjAxNzA1MThfMTU2/MDAxNDk1MDkxMjAzOTAy.O9M2eUuk5H5zhzB3u45Qt2xH4-YWx3DrikIjR3zefFIg.hZCp8Ku494tcefcGmGj6-xXpU-VHwcLSHZf7iJaBTEYg.JPEG/shutterstock_411246616.jpg?type=w1200",
  }),
  RoutineTile.fromMap({
    "id": 4,
    "name": "명상 루틴",
    "description": "명상은 최고의 힐링이자 앞으로 인생의 답을 찾는 좋은 열쇠가 될 것입니다.",
    "time": 4,
    "authority": Authority.admin,
    "difficulty": "중급",
    "type": "정신건강",
    "imageUrl": "https://t1.daumcdn.net/cfile/tistory/99184A445A751DE604",
  }),
  RoutineTile.fromMap({
    "id": 5,
    "name": "홈 트레이닝 운동",
    "description": "집에서도 바깥에서 운동하는 것처럼 충분히 운동할 수 있습니다!",
    "time": 10,
    "authority": Authority.admin,
    "difficulty": "초급",
    "type": "홈 트레이닝",
    "imageUrl": "https://newsimg.sedaily.com/2020/06/08/1Z3Y4474X6_2.jpg",
  }),
  RoutineTile.fromMap({
    "id": 6,
    "name": "등산 루틴",
    "description": "산을 넘는 것은, 스스로의 한계를 넘는 것과 같습니다",
    "time": 120,
    "authority": Authority.admin,
    "difficulty": "중급",
    "type": "건강",
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPj_krP6IsOrxhrXF9Q0AZ-lOBWoYLUD8BaQ&usqp=CAU",
  }),
];